[info]
name = "遗忘の物(Forgotten Item)"
author = "EternalFuture゙"
version = "1.2.0"

[github]
open_source = true
overview = "https://github.com/2079541547"
url = "https://github.com/2079541547/Terraria-EFMod/tree/main/efmod/ForgottenItem"

[platform.windows]
arm64 = false
arm32 = false
x86_64 = false
x86 = false

[platform.android]
arm64 = true
arm32 = true
x86_64 = false
x86 = false

[introduce]
zh-cn = "基于 https://github.com/2099123771/ForgottenItem 的改进版本，添加了已移除物品的获取方式以及某些武器的攻击方式"
zh-hant = "基於 https://github.com/2099123771/ForgottenItem 的改進版本，添加了已移除物品的獲取方式以及某些武器的攻擊方式"
en = "An improved version based on https://github.com/2099123771/ForgottenItem, adding methods to obtain removed items as well as attack patterns for certain weapons."
ja = "https://github.com/2099123771/ForgottenItem を基に改良されたバージョンで、削除されたアイテムの取得方法と特定の武器の攻撃方法が追加されています。"
ko = "https://github.com/2099123771/ForgottenItem 의 개선 버전으로, 제거된 아이템의 획득 방법과 특정 무기의 공격 방식이 추가되었습니다."
it = "Una versione migliorata basata su https://github.com/2099123771/ForgottenItem, che aggiunge i metodi per ottenere gli oggetti rimossi e i modelli d'attacco per certe armi."
es = "Una versión mejorada basada en https://github.com/2099123771/ForgottenItem, añadiendo métodos para obtener objetos eliminados y patrones de ataque para ciertas armas."
fr = "Une version améliorée basée sur https://github.com/2099123771/ForgottenItem, ajoutant les méthodes pour obtenir des objets supprimés ainsi que des modes d'attaque pour certaines armes."
de = "Eine verbesserte Version basierend auf https://github.com/2099123771/ForgottenItem, mit hinzugefügten Methoden zur Beschaffung entfernter Gegenstände sowie Angriffsmustern für bestimmte Waffen."

[[loaders]]
name = "TEFModLoader-EternalFuture゙"
supported_versions = ["2025-05-24"]

[mod]
standards = 20250517
modx = false
